version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo install
  build:
    commands:
      - mvn clean package
      - echo build
  post_build:
    commands:
      - echo post_build
artifacts:
  files:
    - '**/*'
    - target/10-todo-aws-rest-api-h2-0.0.1-SNAPSHOT.jar